# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shutterstock_sdk
from shutterstock_sdk.api.editorial_images_api import EditorialImagesApi  # noqa: E501
from shutterstock_sdk.rest import ApiException


class TestEditorialImagesApi(unittest.TestCase):
    """EditorialImagesApi unit test stubs"""

    def setUp(self):
        self.api = EditorialImagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_editorial_categories(self):
        """Test case for get_editorial_categories

        (Deprecated) List editorial categories  # noqa: E501
        """
        pass

    def test_get_editorial_image(self):
        """Test case for get_editorial_image

        Get editorial content details  # noqa: E501
        """
        pass

    def test_get_editorial_image_0(self):
        """Test case for get_editorial_image_0

        (Deprecated) Get editorial content details  # noqa: E501
        """
        pass

    def test_get_editorial_image_license_list(self):
        """Test case for get_editorial_image_license_list

        List editorial image licenses  # noqa: E501
        """
        pass

    def test_get_editorial_image_livefeed(self):
        """Test case for get_editorial_image_livefeed

        Get editorial livefeed  # noqa: E501
        """
        pass

    def test_get_editorial_image_livefeed_items(self):
        """Test case for get_editorial_image_livefeed_items

        Get editorial livefeed items  # noqa: E501
        """
        pass

    def test_get_editorial_image_livefeed_list(self):
        """Test case for get_editorial_image_livefeed_list

        Get editorial livefeed list  # noqa: E501
        """
        pass

    def test_get_editorial_livefeed(self):
        """Test case for get_editorial_livefeed

        (Deprecated) Get editorial livefeed  # noqa: E501
        """
        pass

    def test_get_editorial_livefeed_items(self):
        """Test case for get_editorial_livefeed_items

        (Deprecated) Get editorial livefeed items  # noqa: E501
        """
        pass

    def test_get_editorial_livefeed_list(self):
        """Test case for get_editorial_livefeed_list

        (Deprecated) Get editorial livefeed list  # noqa: E501
        """
        pass

    def test_get_updated_editorial_images(self):
        """Test case for get_updated_editorial_images

        List updated content  # noqa: E501
        """
        pass

    def test_get_updated_images(self):
        """Test case for get_updated_images

        (Deprecated) List updated content  # noqa: E501
        """
        pass

    def test_license_editorial_image(self):
        """Test case for license_editorial_image

        (Deprecated) License editorial content  # noqa: E501
        """
        pass

    def test_license_editorial_images(self):
        """Test case for license_editorial_images

        License editorial content  # noqa: E501
        """
        pass

    def test_list_editorial_image_categories(self):
        """Test case for list_editorial_image_categories

        List editorial categories  # noqa: E501
        """
        pass

    def test_search_editorial(self):
        """Test case for search_editorial

        (Deprecated) Search editorial content  # noqa: E501
        """
        pass

    def test_search_editorial_images(self):
        """Test case for search_editorial_images

        Search editorial images  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
