# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.videos_api import VideosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVideosApi(unittest.TestCase):
    """VideosApi unit test stubs"""

    def setUp(self):
        self.api = VideosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_video_collection_items(self):
        """Test case for add_video_collection_items

        Add videos to collections  # noqa: E501
        """
        pass

    def test_create_video_collection(self):
        """Test case for create_video_collection

        Create video collections  # noqa: E501
        """
        pass

    def test_delete_video_collection(self):
        """Test case for delete_video_collection

        Delete video collections  # noqa: E501
        """
        pass

    def test_delete_video_collection_items(self):
        """Test case for delete_video_collection_items

        Remove videos from collections  # noqa: E501
        """
        pass

    def test_download_videos(self):
        """Test case for download_videos

        Download videos  # noqa: E501
        """
        pass

    def test_get_featured_video_collection(self):
        """Test case for get_featured_video_collection

        Get the details of featured video collections  # noqa: E501
        """
        pass

    def test_get_featured_video_collection_items(self):
        """Test case for get_featured_video_collection_items

        Get the contents of featured video collections  # noqa: E501
        """
        pass

    def test_get_featured_video_collection_list(self):
        """Test case for get_featured_video_collection_list

        List featured video collections  # noqa: E501
        """
        pass

    def test_get_similar_videos(self):
        """Test case for get_similar_videos

        List similar videos  # noqa: E501
        """
        pass

    def test_get_updated_videos(self):
        """Test case for get_updated_videos

        List updated videos  # noqa: E501
        """
        pass

    def test_get_video(self):
        """Test case for get_video

        Get details about videos  # noqa: E501
        """
        pass

    def test_get_video_collection(self):
        """Test case for get_video_collection

        Get the details of video collections  # noqa: E501
        """
        pass

    def test_get_video_collection_items(self):
        """Test case for get_video_collection_items

        Get the contents of video collections  # noqa: E501
        """
        pass

    def test_get_video_collection_list(self):
        """Test case for get_video_collection_list

        List video collections  # noqa: E501
        """
        pass

    def test_get_video_license_list(self):
        """Test case for get_video_license_list

        List video licenses  # noqa: E501
        """
        pass

    def test_get_video_list(self):
        """Test case for get_video_list

        List videos  # noqa: E501
        """
        pass

    def test_get_video_suggestions(self):
        """Test case for get_video_suggestions

        Get suggestions for a search term  # noqa: E501
        """
        pass

    def test_license_videos(self):
        """Test case for license_videos

        License videos  # noqa: E501
        """
        pass

    def test_list_video_categories(self):
        """Test case for list_video_categories

        List video categories  # noqa: E501
        """
        pass

    def test_rename_video_collection(self):
        """Test case for rename_video_collection

        Rename video collections  # noqa: E501
        """
        pass

    def test_search_videos(self):
        """Test case for search_videos

        Search for videos  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
