# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shutterstock_sdk
from shutterstock_sdk.models.any_of_license_editorial_content_request_country import AnyOfLicenseEditorialContentRequestCountry  # noqa: E501
from shutterstock_sdk.rest import ApiException


class TestAnyOfLicenseEditorialContentRequestCountry(unittest.TestCase):
    """AnyOfLicenseEditorialContentRequestCountry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfLicenseEditorialContentRequestCountry(self):
        """Test AnyOfLicenseEditorialContentRequestCountry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = shutterstock_sdk.models.any_of_license_editorial_content_request_country.AnyOfLicenseEditorialContentRequestCountry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
