# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shutterstock_sdk
from shutterstock_sdk.models.mood_list import MoodList  # noqa: E501
from shutterstock_sdk.rest import ApiException


class TestMoodList(unittest.TestCase):
    """MoodList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMoodList(self):
        """Test MoodList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = shutterstock_sdk.models.mood_list.MoodList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
