# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.oauth_access_token_body import OauthAccessTokenBody  # noqa: E501
from swagger_client.rest import ApiException


class TestOauthAccessTokenBody(unittest.TestCase):
    """OauthAccessTokenBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOauthAccessTokenBody(self):
        """Test OauthAccessTokenBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.oauth_access_token_body.OauthAccessTokenBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
