# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_music_api import CustomMusicApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomMusicApi(unittest.TestCase):
    """CustomMusicApi unit test stubs"""

    def setUp(self):
        self.api = CustomMusicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_audio_renders(self):
        """Test case for create_audio_renders

        Create rendered audio  # noqa: E501
        """
        pass

    def test_fetch_renders(self):
        """Test case for fetch_renders

        Get details about audio renders  # noqa: E501
        """
        pass

    def test_list_custom_descriptors(self):
        """Test case for list_custom_descriptors

        List computer audio descriptors  # noqa: E501
        """
        pass

    def test_list_custom_instruments(self):
        """Test case for list_custom_instruments

        List computer audio instruments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
