# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.audio_render_timeline_span import AudioRenderTimelineSpan  # noqa: E501
from swagger_client.rest import ApiException


class TestAudioRenderTimelineSpan(unittest.TestCase):
    """AudioRenderTimelineSpan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAudioRenderTimelineSpan(self):
        """Test AudioRenderTimelineSpan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.audio_render_timeline_span.AudioRenderTimelineSpan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
