# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.computer_vision_api import ComputerVisionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComputerVisionApi(unittest.TestCase):
    """ComputerVisionApi unit test stubs"""

    def setUp(self):
        self.api = ComputerVisionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_keywords(self):
        """Test case for get_keywords

        List suggested keywords  # noqa: E501
        """
        pass

    def test_get_similar_images(self):
        """Test case for get_similar_images

        List similar images  # noqa: E501
        """
        pass

    def test_get_similar_videos(self):
        """Test case for get_similar_videos

        List similar videos  # noqa: E501
        """
        pass

    def test_upload_ephemeral_image(self):
        """Test case for upload_ephemeral_image

        Upload ephemeral images  # noqa: E501
        """
        pass

    def test_upload_image(self):
        """Test case for upload_image

        Upload images  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
