# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import shutterstock_sdk
from shutterstock_sdk.api.oauth_api import OauthApi  # noqa: E501
from shutterstock_sdk.rest import ApiException


class TestOauthApi(unittest.TestCase):
    """OauthApi unit test stubs"""

    def setUp(self):
        self.api = OauthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authorize(self):
        """Test case for authorize

        Authorize applications  # noqa: E501
        """
        pass

    def test_create_access_token(self):
        """Test case for create_access_token

        Get access tokens  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
