# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.redownload_image import RedownloadImage  # noqa: E501
from swagger_client.rest import ApiException


class TestRedownloadImage(unittest.TestCase):
    """RedownloadImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRedownloadImage(self):
        """Test RedownloadImage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.redownload_image.RedownloadImage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
