# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AudioRenderTimelineSpanTempoChanges(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'float',
        'tempo': 'float'
    }

    attribute_map = {
        'time': 'time',
        'tempo': 'tempo'
    }

    def __init__(self, time=None, tempo=None):  # noqa: E501
        """AudioRenderTimelineSpanTempoChanges - a model defined in Swagger"""  # noqa: E501
        self._time = None
        self._tempo = None
        self.discriminator = None
        self.time = time
        self.tempo = tempo

    @property
    def time(self):
        """Gets the time of this AudioRenderTimelineSpanTempoChanges.  # noqa: E501

        The time, in seconds, at which the tempo exists  # noqa: E501

        :return: The time of this AudioRenderTimelineSpanTempoChanges.  # noqa: E501
        :rtype: float
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this AudioRenderTimelineSpanTempoChanges.

        The time, in seconds, at which the tempo exists  # noqa: E501

        :param time: The time of this AudioRenderTimelineSpanTempoChanges.  # noqa: E501
        :type: float
        """
        if time is None:
            raise ValueError("Invalid value for `time`, must not be `None`")  # noqa: E501

        self._time = time

    @property
    def tempo(self):
        """Gets the tempo of this AudioRenderTimelineSpanTempoChanges.  # noqa: E501

        The tempo, in beats per minute, active at this time  # noqa: E501

        :return: The tempo of this AudioRenderTimelineSpanTempoChanges.  # noqa: E501
        :rtype: float
        """
        return self._tempo

    @tempo.setter
    def tempo(self, tempo):
        """Sets the tempo of this AudioRenderTimelineSpanTempoChanges.

        The tempo, in beats per minute, active at this time  # noqa: E501

        :param tempo: The tempo of this AudioRenderTimelineSpanTempoChanges.  # noqa: E501
        :type: float
        """
        if tempo is None:
            raise ValueError("Invalid value for `tempo`, must not be `None`")  # noqa: E501

        self._tempo = tempo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AudioRenderTimelineSpanTempoChanges, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AudioRenderTimelineSpanTempoChanges):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
