# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AudioRenderTimelineSpanInstrumentGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instrument_group': 'str',
        'statuses': 'list[AudioRenderTimelineSpanInstrumentGroupStatus]'
    }

    attribute_map = {
        'instrument_group': 'instrument_group',
        'statuses': 'statuses'
    }

    def __init__(self, instrument_group=None, statuses=None):  # noqa: E501
        """AudioRenderTimelineSpanInstrumentGroup - a model defined in Swagger"""  # noqa: E501
        self._instrument_group = None
        self._statuses = None
        self.discriminator = None
        self.instrument_group = instrument_group
        if statuses is not None:
            self.statuses = statuses

    @property
    def instrument_group(self):
        """Gets the instrument_group of this AudioRenderTimelineSpanInstrumentGroup.  # noqa: E501

        The instrument ID  # noqa: E501

        :return: The instrument_group of this AudioRenderTimelineSpanInstrumentGroup.  # noqa: E501
        :rtype: str
        """
        return self._instrument_group

    @instrument_group.setter
    def instrument_group(self, instrument_group):
        """Sets the instrument_group of this AudioRenderTimelineSpanInstrumentGroup.

        The instrument ID  # noqa: E501

        :param instrument_group: The instrument_group of this AudioRenderTimelineSpanInstrumentGroup.  # noqa: E501
        :type: str
        """
        if instrument_group is None:
            raise ValueError("Invalid value for `instrument_group`, must not be `None`")  # noqa: E501

        self._instrument_group = instrument_group

    @property
    def statuses(self):
        """Gets the statuses of this AudioRenderTimelineSpanInstrumentGroup.  # noqa: E501

        An array of status objects  # noqa: E501

        :return: The statuses of this AudioRenderTimelineSpanInstrumentGroup.  # noqa: E501
        :rtype: list[AudioRenderTimelineSpanInstrumentGroupStatus]
        """
        return self._statuses

    @statuses.setter
    def statuses(self, statuses):
        """Sets the statuses of this AudioRenderTimelineSpanInstrumentGroup.

        An array of status objects  # noqa: E501

        :param statuses: The statuses of this AudioRenderTimelineSpanInstrumentGroup.  # noqa: E501
        :type: list[AudioRenderTimelineSpanInstrumentGroupStatus]
        """

        self._statuses = statuses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AudioRenderTimelineSpanInstrumentGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AudioRenderTimelineSpanInstrumentGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
