# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EditorialVideoAssets(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'original': 'VideoSizeDetails',
        'preview_mp4': 'VideoPreviewUrl',
        'preview_webm': 'VideoPreviewUrl',
        'thumb_jpg': 'VideoPreviewUrl'
    }

    attribute_map = {
        'original': 'original',
        'preview_mp4': 'preview_mp4',
        'preview_webm': 'preview_webm',
        'thumb_jpg': 'thumb_jpg'
    }

    def __init__(self, original=None, preview_mp4=None, preview_webm=None, thumb_jpg=None):  # noqa: E501
        """EditorialVideoAssets - a model defined in Swagger"""  # noqa: E501
        self._original = None
        self._preview_mp4 = None
        self._preview_webm = None
        self._thumb_jpg = None
        self.discriminator = None
        if original is not None:
            self.original = original
        if preview_mp4 is not None:
            self.preview_mp4 = preview_mp4
        if preview_webm is not None:
            self.preview_webm = preview_webm
        if thumb_jpg is not None:
            self.thumb_jpg = thumb_jpg

    @property
    def original(self):
        """Gets the original of this EditorialVideoAssets.  # noqa: E501


        :return: The original of this EditorialVideoAssets.  # noqa: E501
        :rtype: VideoSizeDetails
        """
        return self._original

    @original.setter
    def original(self, original):
        """Sets the original of this EditorialVideoAssets.


        :param original: The original of this EditorialVideoAssets.  # noqa: E501
        :type: VideoSizeDetails
        """

        self._original = original

    @property
    def preview_mp4(self):
        """Gets the preview_mp4 of this EditorialVideoAssets.  # noqa: E501


        :return: The preview_mp4 of this EditorialVideoAssets.  # noqa: E501
        :rtype: VideoPreviewUrl
        """
        return self._preview_mp4

    @preview_mp4.setter
    def preview_mp4(self, preview_mp4):
        """Sets the preview_mp4 of this EditorialVideoAssets.


        :param preview_mp4: The preview_mp4 of this EditorialVideoAssets.  # noqa: E501
        :type: VideoPreviewUrl
        """

        self._preview_mp4 = preview_mp4

    @property
    def preview_webm(self):
        """Gets the preview_webm of this EditorialVideoAssets.  # noqa: E501


        :return: The preview_webm of this EditorialVideoAssets.  # noqa: E501
        :rtype: VideoPreviewUrl
        """
        return self._preview_webm

    @preview_webm.setter
    def preview_webm(self, preview_webm):
        """Sets the preview_webm of this EditorialVideoAssets.


        :param preview_webm: The preview_webm of this EditorialVideoAssets.  # noqa: E501
        :type: VideoPreviewUrl
        """

        self._preview_webm = preview_webm

    @property
    def thumb_jpg(self):
        """Gets the thumb_jpg of this EditorialVideoAssets.  # noqa: E501


        :return: The thumb_jpg of this EditorialVideoAssets.  # noqa: E501
        :rtype: VideoPreviewUrl
        """
        return self._thumb_jpg

    @thumb_jpg.setter
    def thumb_jpg(self, thumb_jpg):
        """Sets the thumb_jpg of this EditorialVideoAssets.


        :param thumb_jpg: The thumb_jpg of this EditorialVideoAssets.  # noqa: E501
        :type: VideoPreviewUrl
        """

        self._thumb_jpg = thumb_jpg

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EditorialVideoAssets, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditorialVideoAssets):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
