# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EditorialUpdatedContent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'commercial_status': 'EditorialUpdatedContentCommercialStatus',
        'aspect': 'float',
        'assets': 'EditorialAssets',
        'byline': 'str',
        'caption': 'str',
        'categories': 'list[EditorialCategory]',
        'date_taken': 'date',
        'description': 'str',
        'id': 'str',
        'keywords': 'list[str]',
        'title': 'str',
        'updated_time': 'datetime',
        'created_time': 'datetime',
        'rights': 'EditorialUpdatedContentRights',
        'updates': 'list[str]',
        'supplier_code': 'str'
    }

    attribute_map = {
        'commercial_status': 'commercial_status',
        'aspect': 'aspect',
        'assets': 'assets',
        'byline': 'byline',
        'caption': 'caption',
        'categories': 'categories',
        'date_taken': 'date_taken',
        'description': 'description',
        'id': 'id',
        'keywords': 'keywords',
        'title': 'title',
        'updated_time': 'updated_time',
        'created_time': 'created_time',
        'rights': 'rights',
        'updates': 'updates',
        'supplier_code': 'supplier_code'
    }

    def __init__(self, commercial_status=None, aspect=None, assets=None, byline=None, caption=None, categories=None, date_taken=None, description=None, id=None, keywords=None, title=None, updated_time=None, created_time=None, rights=None, updates=None, supplier_code=None):  # noqa: E501
        """EditorialUpdatedContent - a model defined in Swagger"""  # noqa: E501
        self._commercial_status = None
        self._aspect = None
        self._assets = None
        self._byline = None
        self._caption = None
        self._categories = None
        self._date_taken = None
        self._description = None
        self._id = None
        self._keywords = None
        self._title = None
        self._updated_time = None
        self._created_time = None
        self._rights = None
        self._updates = None
        self._supplier_code = None
        self.discriminator = None
        if commercial_status is not None:
            self.commercial_status = commercial_status
        if aspect is not None:
            self.aspect = aspect
        if assets is not None:
            self.assets = assets
        if byline is not None:
            self.byline = byline
        if caption is not None:
            self.caption = caption
        if categories is not None:
            self.categories = categories
        if date_taken is not None:
            self.date_taken = date_taken
        if description is not None:
            self.description = description
        self.id = id
        if keywords is not None:
            self.keywords = keywords
        if title is not None:
            self.title = title
        if updated_time is not None:
            self.updated_time = updated_time
        if created_time is not None:
            self.created_time = created_time
        if rights is not None:
            self.rights = rights
        if updates is not None:
            self.updates = updates
        if supplier_code is not None:
            self.supplier_code = supplier_code

    @property
    def commercial_status(self):
        """Gets the commercial_status of this EditorialUpdatedContent.  # noqa: E501


        :return: The commercial_status of this EditorialUpdatedContent.  # noqa: E501
        :rtype: EditorialUpdatedContentCommercialStatus
        """
        return self._commercial_status

    @commercial_status.setter
    def commercial_status(self, commercial_status):
        """Sets the commercial_status of this EditorialUpdatedContent.


        :param commercial_status: The commercial_status of this EditorialUpdatedContent.  # noqa: E501
        :type: EditorialUpdatedContentCommercialStatus
        """

        self._commercial_status = commercial_status

    @property
    def aspect(self):
        """Gets the aspect of this EditorialUpdatedContent.  # noqa: E501


        :return: The aspect of this EditorialUpdatedContent.  # noqa: E501
        :rtype: float
        """
        return self._aspect

    @aspect.setter
    def aspect(self, aspect):
        """Sets the aspect of this EditorialUpdatedContent.


        :param aspect: The aspect of this EditorialUpdatedContent.  # noqa: E501
        :type: float
        """

        self._aspect = aspect

    @property
    def assets(self):
        """Gets the assets of this EditorialUpdatedContent.  # noqa: E501


        :return: The assets of this EditorialUpdatedContent.  # noqa: E501
        :rtype: EditorialAssets
        """
        return self._assets

    @assets.setter
    def assets(self, assets):
        """Sets the assets of this EditorialUpdatedContent.


        :param assets: The assets of this EditorialUpdatedContent.  # noqa: E501
        :type: EditorialAssets
        """

        self._assets = assets

    @property
    def byline(self):
        """Gets the byline of this EditorialUpdatedContent.  # noqa: E501


        :return: The byline of this EditorialUpdatedContent.  # noqa: E501
        :rtype: str
        """
        return self._byline

    @byline.setter
    def byline(self, byline):
        """Sets the byline of this EditorialUpdatedContent.


        :param byline: The byline of this EditorialUpdatedContent.  # noqa: E501
        :type: str
        """

        self._byline = byline

    @property
    def caption(self):
        """Gets the caption of this EditorialUpdatedContent.  # noqa: E501


        :return: The caption of this EditorialUpdatedContent.  # noqa: E501
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption):
        """Sets the caption of this EditorialUpdatedContent.


        :param caption: The caption of this EditorialUpdatedContent.  # noqa: E501
        :type: str
        """

        self._caption = caption

    @property
    def categories(self):
        """Gets the categories of this EditorialUpdatedContent.  # noqa: E501

        List of categories  # noqa: E501

        :return: The categories of this EditorialUpdatedContent.  # noqa: E501
        :rtype: list[EditorialCategory]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """Sets the categories of this EditorialUpdatedContent.

        List of categories  # noqa: E501

        :param categories: The categories of this EditorialUpdatedContent.  # noqa: E501
        :type: list[EditorialCategory]
        """

        self._categories = categories

    @property
    def date_taken(self):
        """Gets the date_taken of this EditorialUpdatedContent.  # noqa: E501


        :return: The date_taken of this EditorialUpdatedContent.  # noqa: E501
        :rtype: date
        """
        return self._date_taken

    @date_taken.setter
    def date_taken(self, date_taken):
        """Sets the date_taken of this EditorialUpdatedContent.


        :param date_taken: The date_taken of this EditorialUpdatedContent.  # noqa: E501
        :type: date
        """

        self._date_taken = date_taken

    @property
    def description(self):
        """Gets the description of this EditorialUpdatedContent.  # noqa: E501


        :return: The description of this EditorialUpdatedContent.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this EditorialUpdatedContent.


        :param description: The description of this EditorialUpdatedContent.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this EditorialUpdatedContent.  # noqa: E501


        :return: The id of this EditorialUpdatedContent.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EditorialUpdatedContent.


        :param id: The id of this EditorialUpdatedContent.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def keywords(self):
        """Gets the keywords of this EditorialUpdatedContent.  # noqa: E501


        :return: The keywords of this EditorialUpdatedContent.  # noqa: E501
        :rtype: list[str]
        """
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        """Sets the keywords of this EditorialUpdatedContent.


        :param keywords: The keywords of this EditorialUpdatedContent.  # noqa: E501
        :type: list[str]
        """

        self._keywords = keywords

    @property
    def title(self):
        """Gets the title of this EditorialUpdatedContent.  # noqa: E501


        :return: The title of this EditorialUpdatedContent.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this EditorialUpdatedContent.


        :param title: The title of this EditorialUpdatedContent.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def updated_time(self):
        """Gets the updated_time of this EditorialUpdatedContent.  # noqa: E501


        :return: The updated_time of this EditorialUpdatedContent.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_time

    @updated_time.setter
    def updated_time(self, updated_time):
        """Sets the updated_time of this EditorialUpdatedContent.


        :param updated_time: The updated_time of this EditorialUpdatedContent.  # noqa: E501
        :type: datetime
        """

        self._updated_time = updated_time

    @property
    def created_time(self):
        """Gets the created_time of this EditorialUpdatedContent.  # noqa: E501


        :return: The created_time of this EditorialUpdatedContent.  # noqa: E501
        :rtype: datetime
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this EditorialUpdatedContent.


        :param created_time: The created_time of this EditorialUpdatedContent.  # noqa: E501
        :type: datetime
        """

        self._created_time = created_time

    @property
    def rights(self):
        """Gets the rights of this EditorialUpdatedContent.  # noqa: E501


        :return: The rights of this EditorialUpdatedContent.  # noqa: E501
        :rtype: EditorialUpdatedContentRights
        """
        return self._rights

    @rights.setter
    def rights(self, rights):
        """Sets the rights of this EditorialUpdatedContent.


        :param rights: The rights of this EditorialUpdatedContent.  # noqa: E501
        :type: EditorialUpdatedContentRights
        """

        self._rights = rights

    @property
    def updates(self):
        """Gets the updates of this EditorialUpdatedContent.  # noqa: E501


        :return: The updates of this EditorialUpdatedContent.  # noqa: E501
        :rtype: list[str]
        """
        return self._updates

    @updates.setter
    def updates(self, updates):
        """Sets the updates of this EditorialUpdatedContent.


        :param updates: The updates of this EditorialUpdatedContent.  # noqa: E501
        :type: list[str]
        """

        self._updates = updates

    @property
    def supplier_code(self):
        """Gets the supplier_code of this EditorialUpdatedContent.  # noqa: E501


        :return: The supplier_code of this EditorialUpdatedContent.  # noqa: E501
        :rtype: str
        """
        return self._supplier_code

    @supplier_code.setter
    def supplier_code(self, supplier_code):
        """Sets the supplier_code of this EditorialUpdatedContent.


        :param supplier_code: The supplier_code of this EditorialUpdatedContent.  # noqa: E501
        :type: str
        """

        self._supplier_code = supplier_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EditorialUpdatedContent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditorialUpdatedContent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
