# coding: utf-8

"""
    Shutterstock API Explorer

    The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KeywordDataList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'list[str]',
        'errors': 'list[Error]',
        'message': 'str'
    }

    attribute_map = {
        'data': 'data',
        'errors': 'errors',
        'message': 'message'
    }

    def __init__(self, data=None, errors=None, message=None):  # noqa: E501
        """KeywordDataList - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._errors = None
        self._message = None
        self.discriminator = None
        if data is not None:
            self.data = data
        if errors is not None:
            self.errors = errors
        if message is not None:
            self.message = message

    @property
    def data(self):
        """Gets the data of this KeywordDataList.  # noqa: E501

        Keywords  # noqa: E501

        :return: The data of this KeywordDataList.  # noqa: E501
        :rtype: list[str]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this KeywordDataList.

        Keywords  # noqa: E501

        :param data: The data of this KeywordDataList.  # noqa: E501
        :type: list[str]
        """

        self._data = data

    @property
    def errors(self):
        """Gets the errors of this KeywordDataList.  # noqa: E501

        Error list; appears only if there was an error  # noqa: E501

        :return: The errors of this KeywordDataList.  # noqa: E501
        :rtype: list[Error]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this KeywordDataList.

        Error list; appears only if there was an error  # noqa: E501

        :param errors: The errors of this KeywordDataList.  # noqa: E501
        :type: list[Error]
        """

        self._errors = errors

    @property
    def message(self):
        """Gets the message of this KeywordDataList.  # noqa: E501

        Server-generated message, if any  # noqa: E501

        :return: The message of this KeywordDataList.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this KeywordDataList.

        Server-generated message, if any  # noqa: E501

        :param message: The message of this KeywordDataList.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KeywordDataList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeywordDataList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
